user_home: "{{ ansible_user_dir | default(lookup('env','HOME')) }}"
chezmoi_bin: "{{ user_home }}/.local/bin/chezmoi"

dotfiles_repo: "https://github.com/Knot-Here/knot-stow.git"
dotfiles_branch: "main"
