---
- name: Ensure Neovim installed (Arch)
  when: ansible_os_family == "Archlinux"
  pacman:
    name: neovim
    state: present

- name: Ensure Neovim installed (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    name: neovim
    state: present

