---
- name: Update apt cache
  apt:
    update_cache: true

- name: Install common packages (Debian/Ubuntu)
  apt:
    name: "{{ common_packages + debian_packages_extra }}"
    state: present

- name: Install development packages (Debian/Ubuntu)
  apt:
    name: "{{ development_packages | default([]) }}"
    state: present
  when: "'development' in group_names"

- name: Install development GUI packages (Debian/Ubuntu)
  apt:
    name: "{{ dev_gui_packages | default([]) }}"
    state: present
  when: "'development' in group_names"

- name: Install development language packages (Debian/Ubuntu)
  apt:
    name: "{{ dev_lang_packages | default([]) }}"
    state: present
  when: "'development' in group_names"

- name: Install development utility packages (Debian/Ubuntu)
  apt:
    name: "{{ dev_utils_packages | default([]) }}"
    state: present
  when: "'development' in group_names"

