---
- name: Setup Development Environment
  hosts: development
  become: true
  gather_facts: true
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/development.yml

  pre_tasks:
    - name: Debug - Show groups this host belongs to
      debug:
        msg: "This host is in groups: {{ group_names }}"

  roles:
    - base
    - packages
    - development
    - git
    - neovim
    - tmux
    #- chezmoi
